apiVersion: v1
kind: Service
metadata:
  name: request-service-service
spec:
  selector:
    app: request-service
  ports:
    - protocol: TCP
      port: 6002
      targetPort: 6002
      nodePort: 30002     # Порт на узле
  type: NodePort